<?php

namespace Doctrine\Bundle\DoctrineBundle\Repository;

/**
 * FrasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrasesRepository extends \Doctrine\ORM\EntityRepository
{
}
